<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-L3TO6RHS" name="HomePageTest" tests="4" failures="2" timestamp="2 Dec 2017 21:33:59 GMT" time="21.774" errors="0">
  <testcase name="verifyLoginWithInvalidCredentails" time="4.75" classname="com.test.automation.uiAutomation.homepage.TC003_VerifyLoginWithValidCredentails"/>
  <testcase name="verifyLoginWithInvalidCredentails" time="4.767" classname="com.test.automation.uiAutomation.homepage.TC003_VerifyLoginWithValidCredentails">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.test.automation.uiAutomation.customListener.CustomListener.onTestSuccess(CustomListener.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredentails -->
  <testcase name="verifyLoginWithDifferentRecords" time="4.467" classname="com.test.automation.uiAutomation.homepage.TC002_VerifyLoginWithDifferentRecords"/>
  <testcase name="verifyLoginWithDifferentRecords" time="5.102" classname="com.test.automation.uiAutomation.homepage.TC002_VerifyLoginWithDifferentRecords">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.test.automation.uiAutomation.customListener.CustomListener.onTestSuccess(CustomListener.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithDifferentRecords -->
</testsuite> <!-- HomePageTest -->
